# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletOneSuccessPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WMI_ORDER_ID', models.CharField(max_length=255, unique=True)),
                ('WMI_MERCHANT_ID', models.CharField(max_length=255, unique=True)),
                ('WMI_PAYMENT_AMOUNT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('WMI_COMMISSION_AMOUNT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('WMI_CURRENCY_ID', models.IntegerField()),
                ('WMI_TO_USER_ID', models.CharField(max_length=255, unique=True)),
                ('WMI_PAYMENT_NO', models.CharField(blank=True, max_length=255)),
                ('WMI_DESCRIPTION', models.CharField(blank=True, max_length=255)),
                ('WMI_SUCCESS_URL', models.URLField(blank=True)),
                ('WMI_FAIL_URL', models.URLField(blank=True)),
                ('WMI_EXPIRED_DATE', models.DateTimeField(blank=True)),
                ('WMI_CREATE_DATE', models.DateTimeField(blank=True)),
                ('WMI_UPDATE_DATE', models.DateTimeField(blank=True)),
                ('WMI_ORDER_STATE', models.CharField(max_length=255)),
                ('extra_data', models.TextField(blank=True, default='{}')),
            ],
        ),
    ]
