# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletonesuccesspayment',
            name='WMI_MERCHANT_ID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='walletonesuccesspayment',
            name='WMI_TO_USER_ID',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
